apiVersion: v2
name: gitlab-provider-kog-repo
description: A Helm chart for deploying the GitLab KOG Repo.
type: application
version: REPO_CHART_VERSION

home: https://krateo.io
icon: "https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg"
keywords:
  - generator
sources:
  - https://github.com/krateoplatformops-blueprints/gitlab-provider-kog/tree/main/gitlab-provider-kog-repo-blueprint
annotations:
  krateoSupportedVersion: ">= 2.5.1"
