name: main-blueprint-pullrequest

on:
  pull_request:
    branches:
      - main

jobs:
  lint-main-blueprint:
    name: Lint main blueprint chart
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
      
      - name: Ensure yq is installed
        run: |
          if ! command -v yq >/dev/null; then
            YQ_BIN=/usr/local/bin/yq
            sudo curl -sSL "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -o "${YQ_BIN}"
            sudo chmod +x "${YQ_BIN}"
          fi

      - name: Resolve Dependencies
        run: |
          CHART_FILE="./gitlab-provider-kog-blueprint/Chart.yaml"
          HELM_REPO_URL="https://marketplace.krateo.io"
          HELM_REPO_NAME="krateo-marketplace"

          echo "Setting up Helm repository..."
          helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
          helm repo update

          # Replace main chart version for linting
          yq e -i '.version = "0.0.0-lint"' "$CHART_FILE"

          # Dynamically find and replace dependency versions
          for dep_name in $(yq e '.dependencies[].name' "$CHART_FILE"); do
            echo "Resolving version for dependency: $dep_name"
            latest_version=$(helm search repo "${HELM_REPO_NAME}/${dep_name}" -o json | jq -r '.[0].version')
            
            if [ -n "$latest_version" ] && [ "$latest_version" != "null" ]; then
              echo "Found latest version: $latest_version"
              yq e -i "(.dependencies[] | select(.name == \"${dep_name}\")).version = \"${latest_version}\"" "$CHART_FILE"
            else
              echo "Warning: Could not find latest version for ${dep_name}. Linting with a placeholder version."
              yq e -i "(.dependencies[] | select(.name == \"${dep_name}\")).version = \"0.0.0-lint\"" "$CHART_FILE"
              # Not failing for a pull request
            fi
          done

          echo "Chart.yaml after resolving dependencies"
          cat "$CHART_FILE"

      - name: Lint Helm Chart
        run: |
          echo "Linting main blueprint chart..."
          helm lint ./gitlab-provider-kog-blueprint
